/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScootersRouteImport } from './routes/scooters'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvsRouteImport } from './routes/evs'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as BikesRouteImport } from './routes/bikes'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as VehiclesSlugRouteImport } from './routes/vehicles.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScootersRoute = ScootersRouteImport.update({
  id: '/scooters',
  path: '/scooters',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsRoute = EvsRouteImport.update({
  id: '/evs',
  path: '/evs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesRoute = BikesRouteImport.update({
  id: '/bikes',
  path: '/bikes',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesSlugRoute = VehiclesSlugRouteImport.update({
  id: '/vehicles/$slug',
  path: '/vehicles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/bikes': typeof BikesRoute
  '/cars': typeof CarsRoute
  '/compare': typeof CompareRoute
  '/evs': typeof EvsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/reviews': typeof ReviewsRoute
  '/scooters': typeof ScootersRoute
  '/search': typeof SearchRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/vehicles/': typeof VehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/bikes': typeof BikesRoute
  '/cars': typeof CarsRoute
  '/compare': typeof CompareRoute
  '/evs': typeof EvsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/reviews': typeof ReviewsRoute
  '/scooters': typeof ScootersRoute
  '/search': typeof SearchRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/vehicles': typeof VehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/bikes': typeof BikesRoute
  '/cars': typeof CarsRoute
  '/compare': typeof CompareRoute
  '/evs': typeof EvsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/reviews': typeof ReviewsRoute
  '/scooters': typeof ScootersRoute
  '/search': typeof SearchRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/vehicles/': typeof VehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/bikes'
    | '/cars'
    | '/compare'
    | '/evs'
    | '/login'
    | '/news'
    | '/reviews'
    | '/scooters'
    | '/search'
    | '/vehicles/$slug'
    | '/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/bikes'
    | '/cars'
    | '/compare'
    | '/evs'
    | '/login'
    | '/news'
    | '/reviews'
    | '/scooters'
    | '/search'
    | '/vehicles/$slug'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/bikes'
    | '/cars'
    | '/compare'
    | '/evs'
    | '/login'
    | '/news'
    | '/reviews'
    | '/scooters'
    | '/search'
    | '/vehicles/$slug'
    | '/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  BikesRoute: typeof BikesRoute
  CarsRoute: typeof CarsRoute
  CompareRoute: typeof CompareRoute
  EvsRoute: typeof EvsRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  ReviewsRoute: typeof ReviewsRoute
  ScootersRoute: typeof ScootersRoute
  SearchRoute: typeof SearchRoute
  VehiclesSlugRoute: typeof VehiclesSlugRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scooters': {
      id: '/scooters'
      path: '/scooters'
      fullPath: '/scooters'
      preLoaderRoute: typeof ScootersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs': {
      id: '/evs'
      path: '/evs'
      fullPath: '/evs'
      preLoaderRoute: typeof EvsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes': {
      id: '/bikes'
      path: '/bikes'
      fullPath: '/bikes'
      preLoaderRoute: typeof BikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$slug': {
      id: '/vehicles/$slug'
      path: '/vehicles/$slug'
      fullPath: '/vehicles/$slug'
      preLoaderRoute: typeof VehiclesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  BikesRoute: BikesRoute,
  CarsRoute: CarsRoute,
  CompareRoute: CompareRoute,
  EvsRoute: EvsRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  ReviewsRoute: ReviewsRoute,
  ScootersRoute: ScootersRoute,
  SearchRoute: SearchRoute,
  VehiclesSlugRoute: VehiclesSlugRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
